### ISSUE TITLE
Script hanging on QCTools report creation

### ISSUE THREAD

**Issue by BleakleyMcD** [JPC-AV/JPC_AV_videoQC#15]
```
/Users/bleakley/github/JPC_AV/videoqc_jpc_av/JPC_AV
≈:≈ python3 process_file.py /Users/bleakley/Desktop/JPC_AV_00001.mkv       
config.yaml sourced from /Users/bleakley/github/JPC_AV/videoqc_jpc_av/config/config.yaml
command_config.yaml sourced from /Users/bleakley/github/JPC_AV/videoqc_jpc_av/config/command_config.yaml

The file name 'JPC_AV_00001.mkv' is valid.
Video ID, JPC_AV_00001, does not match directory name: Desktop
Metadata files will be written to /Users/bleakley/Desktop/JPC_AV_00001_qc_metadata
No vrecord files found.
Video file not found: /Users/bleakley/Desktop/JPC_AV_04501/JPC_AV_00001.mkv

Using MediaConch policy JPC_AV_NTSC_MKV_2023-11-21.xml
running command: mediaconch -p /Users/bleakley/github/JPC_AV/videoqc_jpc_av/config/JPC_AV_NTSC_MKV_2023-11-21.xml "/Users/bleakley/Desktop/JPC_AV_00001.mkv" -oc /Users/bleakley/Desktop/JPC_AV_00001_qc_metadata/JPC_AV_00001_mediaconch_output.csv
MediaConch policy failed

running command: exiftool "/Users/bleakley/Desktop/JPC_AV_00001.mkv" > /Users/bleakley/Desktop/JPC_AV_00001_qc_metadata/JPC_AV_00001_exiftool_output.txt
All specified fields and values found in the Exiftool output.

running command: mediainfo -f "/Users/bleakley/Desktop/JPC_AV_00001.mkv" > /Users/bleakley/Desktop/JPC_AV_00001_qc_metadata/JPC_AV_00001_mediainfo_output.txt
All specified fields and values found in the MediaInfo output.
The specified MediaInfo fields or values for embedded metadata are below:
metadata field in General: Title does not exist

metadata field in General: Encoded by does not exist

metadata field in General: Description does not exist

metadata field in General: Encoding settings does not exist

metadata field in General: ORIGINAL MEDIA TYPE does not exist


running command: ffprobe -v error -hide_banner -show_format -show_streams -print_format json "/Users/bleakley/Desktop/JPC_AV_00001.mkv" > /Users/bleakley/Desktop/JPC_AV_00001_qc_metadata/JPC_AV_00001_ffprobe_output.txt
No 'encoder settings' in ffprobe output

All specified fields and values found in the ffprobe output.

running command: qcli -i "/Users/bleakley/Desktop/JPC_AV_00001.mkv" -o /Users/bleakley/Desktop/JPC_AV_00001_qc_metadata/JPC_AV_00001.qctools.xml.gz
qcli dev build, Nov 29 2023 02:58:55
filters selected: signalstats psnr astats 
[matroska,webm @ 0x12a605450] Could not find codec parameters for stream 2 (Attachment: none): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x12a605450] Could not find codec parameters for stream 3 (Attachment: none): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options

analyzing input file... /Users/bleakley/Desktop/JPC_AV_00001.mkv
                                                   0 of 100 %
                                                   0 of 100 %
                                                   0 of 100 %

                                                   0 of 100 %^CTraceback (most recent call last):
  File "/Users/bleakley/github/JPC_AV/videoqc_jpc_av/JPC_AV/process_file.py", line 228, in <module>
    main()
  File "/Users/bleakley/github/JPC_AV/videoqc_jpc_av/JPC_AV/process_file.py", line 221, in main
    run_command('qcli -i', video_path, '-o', qctools_output_path)
  File "/Users/bleakley/github/JPC_AV/videoqc_jpc_av/JPC_AV/process_file.py", line 87, in run_command
    subprocess.run(full_command, shell=True)
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 550, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1201, in communicate
    self.wait()
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1264, in wait
    return self._wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 2046, in _wait
    (pid, sts) = self._try_wait(0)
                 ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 2004, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
```
I ran that on a .mkv file that is not from the JPC collection (I faked the filename) and so didn't expect everything to line up but when it hit the QCTools report generation it just hung and clearly there was something it didn't like.

**Comment by eddycolloton** [comment]
I'm not able to reproduce the issue with the 2 sample files I've been testing w/ JPC_AV_05000 and JPC_00011. 

Does qcli run successfully on this file independent of the script? `qcli -i JPC_AV_00001.mkv -o JPC_AV_00001.qctools.xml.gz`

If so, can you send me the file?

**Comment by BleakleyMcD** [comment]
nevermind!
