### ISSUE TITLE
problem with accessing stream hashes in --profile step2

### ISSUE THREAD

**Issue by BleakleyMcD** [JPC-AV/JPC_AV_videoQC#16]
after running step1, which ran good, tried running step2 on the same file and got the below. 

still haven't made it to the QCtools report generation part of step 2.

```
(base) /Users/medialab/github/videoqc_jpc_av/JPC_AV
≈:≈ python process_file.py /Users/medialab/Desktop/JPC_AV_01631_copy/JPC_AV_01631.mkv --profile step2
config.yaml sourced from /Users/medialab/github/videoqc_jpc_av/config/config.yaml
command_config.yaml sourced from /Users/medialab/github/videoqc_jpc_av/config/command_config.yaml
command_config.yaml updated

The file name 'JPC_AV_01631.mkv' is valid.
Video ID, JPC_AV_01631, does not match directory name: JPC_AV_01631_copy
Metadata files will be written to /Users/medialab/Desktop/JPC_AV_01631_copy/JPC_AV_01631_qc_metadata

No vrecord files found.

MD5 checksum found in JPC_AV_01631_2024_02_12_fixity.txt: da26866475adee5d9ed76d80072d2c12
Generating md5 checksum for JPC_AV_01631.mkv via fixity_check.py:
Calculated md5 checksum is da26866475adee5d9ed76d80072d2c12
Fixity check passed for /Users/medialab/Desktop/JPC_AV_01631_copy/JPC_AV_01631.mkv

Extracting existing video and audio stream hashes
Traceback (most recent call last):
  File "/Users/medialab/github/videoqc_jpc_av/JPC_AV/process_file.py", line 266, in <module>
    main()
  File "/Users/medialab/github/videoqc_jpc_av/JPC_AV/process_file.py", line 216, in main
    validate_embedded_md5(video_path)
  File "/Users/medialab/github/videoqc_jpc_av/JPC_AV/embed_fixity.py", line 173, in validate_embedded_md5
    if video_hash is not None:
       ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'video_hash' where it is not associated with a value
                                                                                                                 
(base) /Users/medialab/github/videoqc_jpc_av/JPC_AV
≈:≈ 
```

**Comment by eddycolloton** [comment]
This is a mismatched variable, I had to change the name of video_hash for some reason and missed this reference when updating the code. Should be fixed now: https://github.com/JPC-AV/JPC_AV_videoQC/commit/7d367ba7e214698cbe04e6ecfa5ecf2118e44bd8
