### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by BleakleyMcD** [JPC-AV/JPC_AV_videoQC#2]
```
/Users/bleakley/github/JPC_AV/JPC_AV_videoQC
≈:≈ python mediainfo_check.py /Users/bleakley/JPC_AV_00011_mediainfo.txt 
zsh: command not found: python
                                                                                                                                                                        
/Users/bleakley/github/JPC_AV/JPC_AV_videoQC
≈:≈ python3 mediainfo_check.py /Users/bleakley/JPC_AV_00011_mediainfo.txt 
Traceback (most recent call last):
  File "/Users/bleakley/github/JPC_AV/JPC_AV_videoQC/mediainfo_check.py", line 171, in <module>
    parse_mediainfo(file_path)
  File "/Users/bleakley/github/JPC_AV/JPC_AV_videoQC/mediainfo_check.py", line 68, in parse_mediainfo
    with open(file_path, 'r') as file:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'JPC_AV_00011_mediainfo.txt'
                                                                                                                                                                        
/Users/bleakley/github/JPC_AV/JPC_AV_videoQC
≈:≈ 
```

**Comment by eddycolloton** [comment]
This script is currently set up to just check the file listed inside the script, on line 167 `file_path = ` I'll be adding a script soon that takes the video file as argument, like this: `python [script here] [video file here]` 
That script will make the side cars and check them, but don't quite have it worked out yet.

**Comment by BleakleyMcD** [comment]
Ah ok. So it can't accept other mediainfo output files right now? I can copy the script and modify line 167 for testing done files.

**Comment by eddycolloton** [comment]
Ok, fixed. mediainfo_check.py on main branch will now take mediainfo text file as argument `python3 mediainfo_check.py [some_mediainfo_file.txt]` and will accept either PCM or FLAC as value for "Audio, Format:"
