### ISSUE TITLE
Bowser branch issue: IndexError: list index out of range

### ISSUE THREAD

**Issue by BleakleyMcD** [JPC-AV/JPC_AV_videoQC#23]
```
/Users/bleakley/github/jpc/videoqc_jpc_av
≈:≈ python3 JPC_AV/process_file.py /Users/bleakley/2012_79_2_225_1a_OscarMicheaux
config.yaml sourced from /Users/bleakley/github/jpc/videoqc_jpc_av/config/config.yaml
command_config.yaml sourced from /Users/bleakley/github/jpc/videoqc_jpc_av/config/command_config.yaml
Input directory found: /Users/bleakley/2012_79_2_225_1a_OscarMicheaux

The file name '2012_79_2_225_1a_PM.mkv' is valid.

Input video file found: /Users/bleakley/2012_79_2_225_1a_OscarMicheaux/2012_79_2_225_1a_PM.mkv

|[●▪▪●]| |[●▪▪●]| |[●▪▪●]|

Now processing /Users/bleakley/2012_79_2_225_1a_OscarMicheaux/2012_79_2_225_1a_PM.mkv

Directory name "2012_79_2_225_1a_OscarMicheaux" correctly starts with "2012_79_2_225_1a".

Metadata files will be written to /Users/bleakley/2012_79_2_225_1a_OscarMicheaux/2012_79_2_225_1a_PM_qc_metadata

No vrecord files found.

No video stream hash found
No audio stream hash found

Generating video and audio stream hashes. This may take a moment...
FFmpeg 'streamhash' Progress: 100.00%
Video hash = 8031c3ec1905ad2bf7757db07c3679b1
Audio hash = 9de19ec27b735b37dd3a1bb4e1e9022e

Embedding video and audio stream hashes to XML in MKV file
Running mkvpropedit:
The file is being analyzed.
The changes are written to the file.



Generating md5 checksum for 2012_79_2_225_1a_PM.mkv via fixity_check.py:
Calculated md5 checksum is 51dd8cda22d23cccbcf544c3fbb1ba75

MD5 checksum written to /Users/bleakley/2012_79_2_225_1a_OscarMicheaux/2012_79_2_225_1a_PM_2024_03_08_fixity.txt

Using MediaConch policy JPC_AV_NTSC_MKV_2023-11-21.xml
running command: mediaconch -p /Users/bleakley/github/jpc/videoqc_jpc_av/config/JPC_AV_NTSC_MKV_2023-11-21.xml "/Users/bleakley/2012_79_2_225_1a_OscarMicheaux/2012_79_2_225_1a_PM.mkv" -oc /Users/bleakley/2012_79_2_225_1a_OscarMicheaux/2012_79_2_225_1a_PM_qc_metadata/2012_79_2_225_1a_PM_mediaconch_output.csv

running command: exiftool "/Users/bleakley/2012_79_2_225_1a_OscarMicheaux/2012_79_2_225_1a_PM.mkv" > /Users/bleakley/2012_79_2_225_1a_OscarMicheaux/2012_79_2_225_1a_PM_qc_metadata/2012_79_2_225_1a_PM_exiftool_output.txt
All specified fields and values found in the Exiftool output.

running command: mediainfo -f "/Users/bleakley/2012_79_2_225_1a_OscarMicheaux/2012_79_2_225_1a_PM.mkv" > /Users/bleakley/2012_79_2_225_1a_OscarMicheaux/2012_79_2_225_1a_PM_qc_metadata/2012_79_2_225_1a_PM_mediainfo_output.txt
All specified fields and values found in the MediaInfo output.
The specified MediaInfo fields or values for embedded metadata are below:
metadata field in General: ORIGINAL MEDIA TYPE does not exist


running command: ffprobe -v error -hide_banner -show_format -show_streams -print_format json "/Users/bleakley/2012_79_2_225_1a_OscarMicheaux/2012_79_2_225_1a_PM.mkv" > /Users/bleakley/2012_79_2_225_1a_OscarMicheaux/2012_79_2_225_1a_PM_qc_metadata/2012_79_2_225_1a_PM_ffprobe_output.txt
Traceback (most recent call last):
  File "/Users/bleakley/github/jpc/videoqc_jpc_av/JPC_AV/process_file.py", line 363, in <module>
    main()
  File "/Users/bleakley/github/jpc/videoqc_jpc_av/JPC_AV/process_file.py", line 323, in main
    parse_ffprobe(ffprobe_output_path)
  File "/Users/bleakley/github/jpc/videoqc_jpc_av/JPC_AV/ffprobe_check.py", line 83, in parse_ffprobe
    settings_dict1, settings_dict2, settings_dict3 = parse_encoder_settings(encoder_settings)
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bleakley/github/jpc/videoqc_jpc_av/JPC_AV/encoder_settings_check.py", line 79, in parse_encoder_settings
    key, value = (sublists[2][3].split(' ', 1)[1]).split("=")
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
                                                                                                                                                         
/Users/bleakley/github/jpc/videoqc_jpc_av
≈:≈ 
```

@eddycolloton @emCnabs

**Comment by eddycolloton** [comment]
Closing this, as the "index out of range error" is discussed in issue #24
