### ISSUE TITLE
files in SIP, Bowser branch

### ISSUE THREAD

**Issue by BleakleyMcD** [JPC-AV/JPC_AV_videoQC#24]
files in directory prior to running `process_fily.py` no step indicated:

```/Users/bleakley/github/jpc/videoqc_jpc_av
≈:≈ tree /Users/bleakley/2012_79_2_225_1a_OscarMicheaux
/Users/bleakley/2012_79_2_225_1a_OscarMicheaux
├── 2012_79_2_225_1a_OscarMicheaux_contents_.txt
├── 2012_79_2_225_1a_PM.framemd5
├── 2012_79_2_225_1a_PM.mkv
├── 2012_79_2_225_1a_PM.mkv.qctools.mkv
├── 2012_79_2_225_1a_PM_MKV_2024-02-08_checksums.md5
├── 2012_79_2_225_1a_PM_MKV_mediainfo.txt
├── 2012_79_2_225_1a_PM_QC_output_graphs.jpeg
├── 2012_79_2_225_1a_PM_capture_options.log
├── 2012_79_2_225_1a_PM_mediainfo.txt
└── 2012_79_2_225_1a_PM_vrecord_input.log

1 directory, 10 files
```
files in directory after running `process_file.py`

```
/Users/bleakley/github/jpc/videoqc_jpc_av
≈:≈ tree /Users/bleakley/2012_79_2_225_1a_OscarMicheaux 
/Users/bleakley/2012_79_2_225_1a_OscarMicheaux
├── 2012_79_2_225_1a_OscarMicheaux_contents_.txt
├── 2012_79_2_225_1a_PM.framemd5
├── 2012_79_2_225_1a_PM.mkv
├── 2012_79_2_225_1a_PM.mkv.qctools.mkv
├── 2012_79_2_225_1a_PM_2024_03_08_fixity.txt
├── 2012_79_2_225_1a_PM_MKV_2024-02-08_checksums.md5
├── 2012_79_2_225_1a_PM_MKV_mediainfo.txt
├── 2012_79_2_225_1a_PM_QC_output_graphs.jpeg
├── 2012_79_2_225_1a_PM_capture_options.log
├── 2012_79_2_225_1a_PM_mediainfo.txt
├── 2012_79_2_225_1a_PM_qc_metadata
│   ├── 2012_79_2_225_1a_PM_exiftool_output.txt
│   ├── 2012_79_2_225_1a_PM_ffprobe_output.txt
│   ├── 2012_79_2_225_1a_PM_mediaconch_output.csv
│   └── 2012_79_2_225_1a_PM_mediainfo_output.txt
└── 2012_79_2_225_1a_PM_vrecord_input.log

2 directories, 15 files
```

terminal output during script run - please note it did exit with an error and did, perhaps, not finish:
```
/Users/bleakley/github/jpc/videoqc_jpc_av
≈:≈ python3 JPC_AV/process_file.py /Users/bleakley/2012_79_2_225_1a_OscarMicheaux
config.yaml sourced from /Users/bleakley/github/jpc/videoqc_jpc_av/config/config.yaml
command_config.yaml sourced from /Users/bleakley/github/jpc/videoqc_jpc_av/config/command_config.yaml
Input directory found: /Users/bleakley/2012_79_2_225_1a_OscarMicheaux

The file name '2012_79_2_225_1a_PM.mkv' is valid.

Input video file found: /Users/bleakley/2012_79_2_225_1a_OscarMicheaux/2012_79_2_225_1a_PM.mkv

|[●▪▪●]| |[●▪▪●]| |[●▪▪●]|

Now processing /Users/bleakley/2012_79_2_225_1a_OscarMicheaux/2012_79_2_225_1a_PM.mkv

Directory name "2012_79_2_225_1a_OscarMicheaux" correctly starts with "2012_79_2_225_1a".

Metadata files will be written to /Users/bleakley/2012_79_2_225_1a_OscarMicheaux/2012_79_2_225_1a_PM_qc_metadata

No vrecord files found.

No video stream hash found
No audio stream hash found

Generating video and audio stream hashes. This may take a moment...
FFmpeg 'streamhash' Progress: 100.00%
Video hash = 8031c3ec1905ad2bf7757db07c3679b1
Audio hash = 9de19ec27b735b37dd3a1bb4e1e9022e

Embedding video and audio stream hashes to XML in MKV file
Running mkvpropedit:
The file is being analyzed.
The changes are written to the file.



Generating md5 checksum for 2012_79_2_225_1a_PM.mkv via fixity_check.py:
Calculated md5 checksum is 51dd8cda22d23cccbcf544c3fbb1ba75

MD5 checksum written to /Users/bleakley/2012_79_2_225_1a_OscarMicheaux/2012_79_2_225_1a_PM_2024_03_08_fixity.txt

Using MediaConch policy JPC_AV_NTSC_MKV_2023-11-21.xml
running command: mediaconch -p /Users/bleakley/github/jpc/videoqc_jpc_av/config/JPC_AV_NTSC_MKV_2023-11-21.xml "/Users/bleakley/2012_79_2_225_1a_OscarMicheaux/2012_79_2_225_1a_PM.mkv" -oc /Users/bleakley/2012_79_2_225_1a_OscarMicheaux/2012_79_2_225_1a_PM_qc_metadata/2012_79_2_225_1a_PM_mediaconch_output.csv

running command: exiftool "/Users/bleakley/2012_79_2_225_1a_OscarMicheaux/2012_79_2_225_1a_PM.mkv" > /Users/bleakley/2012_79_2_225_1a_OscarMicheaux/2012_79_2_225_1a_PM_qc_metadata/2012_79_2_225_1a_PM_exiftool_output.txt
All specified fields and values found in the Exiftool output.

running command: mediainfo -f "/Users/bleakley/2012_79_2_225_1a_OscarMicheaux/2012_79_2_225_1a_PM.mkv" > /Users/bleakley/2012_79_2_225_1a_OscarMicheaux/2012_79_2_225_1a_PM_qc_metadata/2012_79_2_225_1a_PM_mediainfo_output.txt
All specified fields and values found in the MediaInfo output.
The specified MediaInfo fields or values for embedded metadata are below:
metadata field in General: ORIGINAL MEDIA TYPE does not exist


running command: ffprobe -v error -hide_banner -show_format -show_streams -print_format json "/Users/bleakley/2012_79_2_225_1a_OscarMicheaux/2012_79_2_225_1a_PM.mkv" > /Users/bleakley/2012_79_2_225_1a_OscarMicheaux/2012_79_2_225_1a_PM_qc_metadata/2012_79_2_225_1a_PM_ffprobe_output.txt
Traceback (most recent call last):
  File "/Users/bleakley/github/jpc/videoqc_jpc_av/JPC_AV/process_file.py", line 363, in <module>
    main()
  File "/Users/bleakley/github/jpc/videoqc_jpc_av/JPC_AV/process_file.py", line 323, in main
    parse_ffprobe(ffprobe_output_path)
  File "/Users/bleakley/github/jpc/videoqc_jpc_av/JPC_AV/ffprobe_check.py", line 83, in parse_ffprobe
    settings_dict1, settings_dict2, settings_dict3 = parse_encoder_settings(encoder_settings)
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bleakley/github/jpc/videoqc_jpc_av/JPC_AV/encoder_settings_check.py", line 79, in parse_encoder_settings
    key, value = (sublists[2][3].split(' ', 1)[1]).split("=")
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
                                                                                                                                                         
/Users/bleakley/github/jpc/videoqc_jpc_av
≈:≈ 
```

note `No vrecord files found.` the script does not recognize the vrecord files in the SIP, probably due to naming format requirements.
@EmCNabs - there are two mediainfo files in the SIP prior to script run: `2012_79_2_225_1a_PM_MKV_mediainfo.txt` and `2012_79_2_225_1a_PM_mediainfo.txt` which appear identical. Accidental duplicate? In the new workflow, you won't need to make a mediainfo output file, the script will do it.

The script also did not recognize `2012_79_2_225_1a_PM_MKV_2024-02-08_checksums.md5` again probably due to naming conformance issues. @EmCNabs in the new workflow you won't need to make the checksum (unless you want to) because the script will do it.

@eddycolloton

**Comment by eddycolloton** [comment]
The vrecord files is an easy fix. The check had a requirement for "JPC_AV_" in filename along with ending with vrecord suffixes: '_QC_output_graphs.jpeg', '_vrecord_input.log', '_capture_options.log', '.mkv.qctools.mkv', '.framemd5'

Removed JPC_AV_ part which will hopefully address that problem.

The error it was exiting on, IndexError: list index out of range, is because the encoder settings in this file and the one I based the encoder_settings_check.py on are different. 

Here's JPC_AV_05000.mkv:
"O=VHS, C=Color, S=Analog, VS= NTSC, F=24, A=4:3, R=640×480, T=Sony SVO-5800, O=FFV1mkv, C=Color, V=Composite, S=Analog Stereo, F=24, A=4:3, W=10-bit, R=640×480, M=YUV422p10, T=Blackmagic UltraStudio 4K Mini SN123456, ffmpeg vrecord; in-house, O=FFV1mkv, W=10-bit, R640x480, MYUV422p10 N=AJ Lawrence"

Here's 2012_79_2_225_1a_PM.mkv:
"O=VHS, C=Color, S=Analog, VS= NTSC, F=24, A=4:3, R=720x486, T=Sony SVO-5800, O=FFV1mkv, C=Color, V=Composite, S=Analog Stereo, F=24, A=4:3, W=10-bit, R=720x486, M=YUV422p10, T=Blackmagic UltraStudio 4K Mini SN123456, ffmpeg vrecord; in-house, O=FFV1mkv, W=10-bit, R=720x486, M=YUV422p10, N=Emily Nabasny"

Notice the last few fields from JPC_AV_0500 don't have "=", and the last one is missing the comma. So I made up a fancy way of parsing the last few fields for the JPC stuff because I couldn't use "=" or ",". The "list index out of range" error is that bit of code looking for more junk on the end of the encoder settings that isn't there on 2012_79_2_225_1a_PM.mkv. 

I'll update the JPC_AV branch to not freak out if the encoder settings don't line up to avoid it hard exiting...

Commit details here:
https://github.com/JPC-AV/JPC_AV_videoQC/commit/6bde50b289dc9df88c0525a79efcf815fe524d07

**Comment by eddycolloton** [comment]
I believe this issue is closed with fixes mentioned here and in other closed branch about the list index being out of range.
