### ISSUE TITLE
missing module 'art'

### ISSUE THREAD

**Issue by BleakleyMcD** [JPC-AV/JPC_AV_videoQC#27]
```
/Users/medialab/github/jpc_av/videoqc_jpcav/AV_Spex
≈:≈ python3 process_av.py /Volumes/JPCARCHIVE/00_fromDMZ/upload/DCvideo/JPC_AV_00001/JPC_AV_00001.mkv 
Traceback (most recent call last):
  File "/Users/medialab/github/jpc_av/videoqc_jpcav/AV_Spex/process_av.py", line 14, in <module>
    from art import *
ModuleNotFoundError: No module named 'art'
```
So

```
/Users/medialab/github/jpc_av/videoqc_jpcav
≈:≈ pip install -r requirements.txt
Requirement already satisfied: PyYAML==6.0.1 in /usr/local/anaconda3/lib/python3.11/site-packages (from -r requirements.txt (line 1)) (6.0.1)
Requirement already satisfied: colorlog==6.7.0 in /usr/local/anaconda3/lib/python3.11/site-packages (from -r requirements.txt (line 2)) (6.7.0)
Requirement already satisfied: art==6.1 in /usr/local/anaconda3/lib/python3.11/site-packages (from -r requirements.txt (line 3)) (6.1)
```
hmmm...

```
/Users/medialab/github/jpc_av/videoqc_jpcav
≈:≈ git pull
Already up to date.
```
and

```
/Users/medialab/github/jpc_av/videoqc_jpcav/AV_Spex
≈:≈ python3 process_av.py /Volumes/JPCARCHIVE/00_fromDMZ/upload/DCvideo/JPC_AV_00001/JPC_AV_00001.mkv 
Traceback (most recent call last):
  File "/Users/medialab/github/jpc_av/videoqc_jpcav/AV_Spex/process_av.py", line 14, in <module>
    from art import *
ModuleNotFoundError: No module named 'art'
```

dang. This is on a computer at work, not my laptop where everything seems to be fine. Maybe an issue with $PATH?

**Comment by eddycolloton** [comment]
yes I suspect PATH, pip and python3 looking in the wrong place or something. Is this in a conda env? if you run "which pip" and "which python3" are they in the same dir? Is "which pip3" in the same dir as "python3"?

**Comment by BleakleyMcD** [comment]
Yeah... our default PATH was ancient. Updated the PATH but haven't check this yet. Will reopen if still an issue.
