### ISSUE TITLE
Unable to create Access File

### ISSUE THREAD

**Issue by EmCNabs** [JPC-AV/JPC_AV_videoQC#48]
Testing out av-spex on a Bowser directory and ran into an error trying to generate an access file via  --profile step 1

```
Running ffmpeg on 2012_79_2_224_1a_PM.mkv to create access copy 2012_79_2_224_1a_PM_access.mp4

Traceback (most recent call last):
  File "/usr/local/anaconda3/bin/av-spex", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/medialab/github/jpc/videoqc_jpc/src/AV_Spex/av_spex_the_file.py", line 496, in main
    make_access_file(video_path, access_output_path)
  File "/Users/medialab/github/jpc/videoqc_jpc/src/AV_Spex/checks/make_access.py", line 51, in make_access_file
    current_frame_ms = float(current_frame_str)
                       ^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'N/A'
```

**Comment by eddycolloton** [comment]
I think this is bad error handling on my part. The script is grabbing the ffmpeg output, and if it is anything other than a normal output, it just crashes. 

Surprised it hasn't happened sooner! 

Could you send me this mkv file? 

Could you run this ffmpeg command on 2012_79_2_224_1a_PM.mkv on its own?

ffmpeg -i 2012_79_2_224_1a_PM.mkv -movflags faststart -map 0:v -map 0:a? -c:v libx264 -vf yadif=1,format=yuv420p -crf 18 -preset fast -maxrate 1000k -bufsize 1835k -c:a aac -strict -2 -b:a 192k -f mp4 "[[some output_path.mp4]]"

**Comment by EmCNabs** [comment]
ffmpeg command test run

```
/Users/medialab/Desktop/JPC_AV_Tests/2012_79_2_224_1a_PM
≈:≈ ffmpeg -i 2012_79_2_224_1a_PM.mkv -movflags faststart -map 0:v -map 0:a? -c:v libx264 -vf yadif=1,format=yuv420p -crf 18 -preset fast -maxrate 1000k -bufsize 1835k -c:a aac -strict -2 -b:a 192k -f mp4 2012_79_2_224_1a_PM_AccessTest.mp4
zsh: no matches found: 0:a?
```
sending you a link to the file

**Comment by eddycolloton** [comment]
interesting. If that's the error ffmpeg is getting when it is run through av-spex's python script, that would explain the issue. 

This looks like it is a zsh error and not an ffmpeg error, so my current process for grabbing the ffmpeg output in order to calculate a progress percentage definitely wouldn't correctly report this out. 

I was able to download the files from the link you shared to my outlook. I'll do some tests and follow up tomorrow.

**Comment by eddycolloton** [comment]
As of this [commit](https://github.com/JPC-AV/JPC_AV_videoQC/commit/27c717607321d2c59fab2a747d614b0e4b589321), if there is an error in the ffmpeg process than av-spex will not hard exit, and just continue running.

Not quite sure what's causing this file tobreak the access copy command. 

With this command, I get the same zsh error as you 
```
ffmpeg -i 2012_79_2_224_1a_PM.mkv -movflags faststart -map 0:v -map 0:a? -c:v libx264 -vf yadif=1,format=yuv420p -crf 18 -preset fast -maxrate 1000k -bufsize 1835k -c:a aac -strict -2 -b:a 192k -f mp4 test_72_2_224_1a_PM_quotations.mp4
zsh: no matches found: 0:a?
```

If I put quotation marks around '0:a?', I get an ffmpeg error:
```
ffmpeg -i 2012_79_2_224_1a_PM.mkv -movflags faststart -map 0:v -map '0:a?' -c:v libx264 -vf yadif=1,format=yuv420p -crf 18 -preset fast -maxrate 1000k -bufsize 1835k -c:a aac -strict -2 -b:a 192k -f mp4 test_72_2_224_1a_PM_quotations.mp4


ffmpeg version 7.0.1 Copyright (c) 2000-2024 the FFmpeg developers
  built with Apple clang version 15.0.0 (clang-1500.3.9.4)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/7.0.1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
[matroska,webm @ 0x11ee05070] Stream #4: not enough frames to estimate rate; consider increasing probesize
[matroska,webm @ 0x11ee05070] Could not find codec parameters for stream 2 (Attachment: none): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x11ee05070] Could not find codec parameters for stream 3 (Attachment: none): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Input #0, matroska,webm, from '2012_79_2_224_1a_PM.mkv':
  Metadata:
    AUDIO_STREAM_HASH: 61ffbdd7ec66221a72d9d3baac1cf4b0
    creation_time   : 2024-02-26T17:44:59.358149Z
    VIDEO_STREAM_HASH: 3fdb51da2c7ee171710d96239f71bd90
    ENCODER         : Lavf60.3.100
    title           : Midnight Ramble: Oscar Micheaux Clips
  Duration: 00:15:00.03, start: 0.000000, bitrate: 86801 kb/s
  Stream #0:0: Video: ffv1 (FFV1 / 0x31564646), yuv422p10le(tv, smpte170m/smpte170m/bt709, bottom coded first (swapped)), 720x486, SAR 9:10 DAR 4:3, 29.97 fps, 29.97 tbr, 1k tbn
      Metadata:
        ENCODER         : FFV1 version 3
        DURATION        : 00:15:00.032000000
  Stream #0:1: Audio: flac, 48000 Hz, stereo, s32 (24 bit)
      Metadata:
        ENCODER         : Lavc60.3.100 flac
        DURATION        : 00:15:00.000000000
  Stream #0:2: Attachment: none
      Metadata:
        filename        : 2012_79_2_224_1a_PM_capture_options.log
        mimetype        : text/x-log
        title           : Capture options selected by user during vrecord process
  Stream #0:3: Attachment: none
      Metadata:
        filename        : 2012_79_2_224_1a_PM_vrecord_input.log
        mimetype        : text/x-log
        title           : Full FFmpeg output from vrecord capture process
  Stream #0:4: Video: mjpeg (Baseline), yuvj444p(pc, bt470bg/unknown/unknown), 1920x1080 [SAR 96:96 DAR 16:9], 90k tbr, 90k tbn (attached pic)
      Metadata:
        filename        : 2012_79_2_224_1a_PM_QC_output_graphs.jpeg
        mimetype        : image/jpeg
Stream mapping:
  Stream #0:0 -> #0:0 (ffv1 (native) -> h264 (libx264))
  Stream #0:4 -> #0:1 (mjpeg (native) -> h264 (libx264))
  Stream #0:1 -> #0:2 (flac (native) -> aac (native))
Press [q] to stop, [?] for help
[swscaler @ 0x130270000] deprecated pixel format used, make sure you did set range correctly
[libx264 @ 0x11f809370] using SAR=9/10
[libx264 @ 0x11f809370] using cpu capabilities: ARMv8 NEON
[libx264 @ 0x11f809370] profile High, level 3.1, 4:2:0, 8-bit
[libx264 @ 0x11f809370] 264 - core 164 r3108 31e19f9 - H.264/MPEG-4 AVC codec - Copyleft 2003-2023 - http://www.videolan.org/x264.html - options: cabac=1 ref=2 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=6 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=15 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=1 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=30 rc=crf mbtree=1 crf=18.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 vbv_maxrate=1000 vbv_bufsize=1835 crf_max=0.0 nal_hrd=none filler=0 ip_ratio=1.40 aq=1:1.00

[swscaler @ 0x12b900000] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x148a80000] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x110810000] deprecated pixel format used, make sure you did set range correctly
[libx264 @ 0x11f8121b0] using SAR=1/1
[libx264 @ 0x11f8121b0] MB rate (1468800000) > level limit (16711680)
[libx264 @ 0x11f8121b0] using cpu capabilities: ARMv8 NEON
[libx264 @ 0x11f8121b0] profile High, level 6.2, 4:2:0, 8-bit
[libx264 @ 0x11f8121b0] 264 - core 164 r3108 31e19f9 - H.264/MPEG-4 AVC codec - Copyleft 2003-2023 - http://www.videolan.org/x264.html - options: cabac=1 ref=2 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=6 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=16 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=1 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=30 rc=crf mbtree=1 crf=18.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 vbv_maxrate=1000 vbv_bufsize=1835 crf_max=0.0 nal_hrd=none filler=0 ip_ratio=1.40 aq=1:1.00
[mp4 @ 0x11f807800] Could not find tag for codec h264 in stream #1, codec not currently supported in container
[out#0/mp4 @ 0x600000df40c0] Could not write header (incorrect codec parameters ?): Invalid argument
[vf#0:1 @ 0x600000af4120] Error sending frames to consumers: Invalid argument
[vf#0:1 @ 0x600000af4120] Task finished with error code: -22 (Invalid argument)
[vf#0:1 @ 0x600000af4120] Terminating thread with return code -22 (Invalid argument)
[out#0/mp4 @ 0x600000df40c0] Nothing was written into output file, because at least one of its streams received no packets.
frame=    0 fps=0.0 q=-1.0 Lq=0.0 size=       0KiB time=N/A bitrate=N/A dup=2 drop=0 speed=N/A    
[libx264 @ 0x11f809370] frame I:449   Avg QP:27.73  size:  6827
[libx264 @ 0x11f809370] frame P:15352 Avg QP:29.72  size:  2990
[libx264 @ 0x11f809370] frame B:38147 Avg QP:32.08  size:  1667
[libx264 @ 0x11f809370] consecutive B-frames:  5.3%  1.0%  0.8% 92.9%
[libx264 @ 0x11f809370] mb I  I16..4: 28.4% 65.5%  6.1%
[libx264 @ 0x11f809370] mb P  I16..4:  3.3%  3.1%  0.1%  P16..4: 51.4%  8.2%  3.8%  0.0%  0.0%    skip:30.1%
[libx264 @ 0x11f809370] mb B  I16..4:  3.2%  6.0%  0.0%  B16..8: 20.9%  1.7%  0.0%  direct:23.2%  skip:45.0%  L0:50.3% L1:47.1% BI: 2.6%
[libx264 @ 0x11f809370] 8x8 transform intra:61.8% inter:92.7%
[libx264 @ 0x11f809370] coded y,uvDC,uvAC intra: 24.6% 32.6% 1.6% inter: 11.3% 26.3% 0.1%
[libx264 @ 0x11f809370] i16 v,h,dc,p: 30% 41% 11% 18%
[libx264 @ 0x11f809370] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 12% 26% 44%  2%  3%  2%  4%  2%  3%
[libx264 @ 0x11f809370] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 27% 35% 13%  4%  5%  4%  5%  3%  3%
[libx264 @ 0x11f809370] i8c dc,h,v,p: 79% 14%  7%  1%
[libx264 @ 0x11f809370] Weighted P-Frames: Y:41.6% UV:8.7%
[libx264 @ 0x11f809370] ref P L0: 50.3% 49.7%
[libx264 @ 0x11f809370] ref B L0: 68.7% 31.3%
[libx264 @ 0x11f809370] ref B L1: 87.0% 13.0%
[libx264 @ 0x11f809370] kb/s:1000.62
[aac @ 0x11f814c50] Qavg: 672.218
Conversion failed!
```

Here's your issue: ` Stream #0:4 -> #0:1 (mjpeg (native) -> h264 (libx264))`

I think ffmpeg is grabbing the embedded 2012_79_2_224_1a_PM_QC_output_graphs.jpeg file and trying to treat it as video or something. 

If you remove both -map flags all together the embedded jpeg is just discarded, and the file is created:
```
ffmpeg -i 2012_79_2_224_1a_PM.mkv -movflags faststart -c:v libx264 -vf yadif=1,format=yuv420p -crf 18 -preset fast -maxrate 1000k -bufsize 1835k -c:a aac -strict -2 -b:a 192k -f mp4 test_72_2_224_1a_PM_no_mapping.mp4 
ffmpeg version 7.0.1 Copyright (c) 2000-2024 the FFmpeg developers
  built with Apple clang version 15.0.0 (clang-1500.3.9.4)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/7.0.1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
[matroska,webm @ 0x143805450] Stream #4: not enough frames to estimate rate; consider increasing probesize
[matroska,webm @ 0x143805450] Could not find codec parameters for stream 2 (Attachment: none): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x143805450] Could not find codec parameters for stream 3 (Attachment: none): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Input #0, matroska,webm, from '2012_79_2_224_1a_PM.mkv':
  Metadata:
    AUDIO_STREAM_HASH: 61ffbdd7ec66221a72d9d3baac1cf4b0
    creation_time   : 2024-02-26T17:44:59.358149Z
    VIDEO_STREAM_HASH: 3fdb51da2c7ee171710d96239f71bd90
    ENCODER         : Lavf60.3.100
    title           : Midnight Ramble: Oscar Micheaux Clips
  Duration: 00:15:00.03, start: 0.000000, bitrate: 86801 kb/s
  Stream #0:0: Video: ffv1 (FFV1 / 0x31564646), yuv422p10le(tv, smpte170m/smpte170m/bt709, bottom coded first (swapped)), 720x486, SAR 9:10 DAR 4:3, 29.97 fps, 29.97 tbr, 1k tbn
      Metadata:
        ENCODER         : FFV1 version 3
        DURATION        : 00:15:00.032000000
  Stream #0:1: Audio: flac, 48000 Hz, stereo, s32 (24 bit)
      Metadata:
        ENCODER         : Lavc60.3.100 flac
        DURATION        : 00:15:00.000000000
  Stream #0:2: Attachment: none
      Metadata:
        filename        : 2012_79_2_224_1a_PM_capture_options.log
        mimetype        : text/x-log
        title           : Capture options selected by user during vrecord process
  Stream #0:3: Attachment: none
      Metadata:
        filename        : 2012_79_2_224_1a_PM_vrecord_input.log
        mimetype        : text/x-log
        title           : Full FFmpeg output from vrecord capture process
  Stream #0:4: Video: mjpeg (Baseline), yuvj444p(pc, bt470bg/unknown/unknown), 1920x1080 [SAR 96:96 DAR 16:9], 90k tbr, 90k tbn (attached pic)
      Metadata:
        filename        : 2012_79_2_224_1a_PM_QC_output_graphs.jpeg
        mimetype        : image/jpeg
Stream mapping:
  Stream #0:0 -> #0:0 (ffv1 (native) -> h264 (libx264))
  Stream #0:1 -> #0:1 (flac (native) -> aac (native))
Press [q] to stop, [?] for help
[libx264 @ 0x143809bf0] using SAR=9/10
[libx264 @ 0x143809bf0] using cpu capabilities: ARMv8 NEON
[libx264 @ 0x143809bf0] profile High, level 3.1, 4:2:0, 8-bit
[libx264 @ 0x143809bf0] 264 - core 164 r3108 31e19f9 - H.264/MPEG-4 AVC codec - Copyleft 2003-2023 - http://www.videolan.org/x264.html - options: cabac=1 ref=2 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=6 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=15 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=1 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=30 rc=crf mbtree=1 crf=18.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 vbv_maxrate=1000 vbv_bufsize=1835 crf_max=0.0 nal_hrd=none filler=0 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to 'test_72_2_224_1a_PM_no_mapping.mp4':
  Metadata:
    AUDIO_STREAM_HASH: 61ffbdd7ec66221a72d9d3baac1cf4b0
    title           : Midnight Ramble: Oscar Micheaux Clips
    VIDEO_STREAM_HASH: 3fdb51da2c7ee171710d96239f71bd90
    encoder         : Lavf61.1.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, smpte170m/smpte170m/bt709, progressive), 720x486 [SAR 9:10 DAR 4:3], q=2-31, 59.94 fps, 60k tbn
      Metadata:
        DURATION        : 00:15:00.032000000
        encoder         : Lavc61.3.100 libx264
      Side data:
        cpb: bitrate max/min/avg: 1000000/0/0 buffer size: 1835000 vbv_delay: N/A
  Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 192 kb/s
      Metadata:
        DURATION        : 00:15:00.000000000
        encoder         : Lavc61.3.100 aac
frame=   83 fps=0.0 q=30.0 size=       0KiB time=00:00:01.35 bitrate=   0.3kbitsframe=  218 fps=217 q=31.0 size=     512KiB time=00:00:03.60 bitrate=1164.0kbitsframe=  350 fps=232 q=31.0 size=     768KiB time=00:00:05.80 bitrate=1083.7kbitsframe=  475 fps=236 q=31.0 size=    1024KiB time=00:00:07.89 bitrate=1063.1kbits
```
...etc...
```
frame=53742 fps=316 q=30.0 size=  130560KiB time=00:14:56.56 bitrate=1192.9kbitsframe=53877 fps=316 q=30.0 size=  130816KiB time=00:14:58.81 bitrate=1192.3kbits[mp4 @ 0x143807d00] Starting second pass: moving the moov atom to the beginning of the file
[out#0/mp4 @ 0x6000005e80c0] video:109939KiB audio:21202KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: 1.056102%
frame=53948 fps=316 q=-1.0 Lsize=  132526KiB time=00:14:59.99 bitrate=1206.3kbits/s dup=2 drop=0 speed=5.27x    
[libx264 @ 0x143809bf0] frame I:449   Avg QP:27.73  size:  6828
[libx264 @ 0x143809bf0] frame P:15352 Avg QP:29.71  size:  2991
[libx264 @ 0x143809bf0] frame B:38147 Avg QP:32.07  size:  1667
[libx264 @ 0x143809bf0] consecutive B-frames:  5.3%  1.0%  0.8% 92.9%
[libx264 @ 0x143809bf0] mb I  I16..4: 28.5% 65.4%  6.2%
[libx264 @ 0x143809bf0] mb P  I16..4:  3.2%  3.1%  0.1%  P16..4: 51.4%  8.2%  3.8%  0.0%  0.0%    skip:30.1%
[libx264 @ 0x143809bf0] mb B  I16..4:  3.2%  6.0%  0.0%  B16..8: 20.9%  1.7%  0.0%  direct:23.2%  skip:45.0%  L0:50.3% L1:47.0% BI: 2.6%
[libx264 @ 0x143809bf0] 8x8 transform intra:61.8% inter:92.7%
[libx264 @ 0x143809bf0] coded y,uvDC,uvAC intra: 24.7% 32.6% 1.6% inter: 11.3% 26.3% 0.1%
[libx264 @ 0x143809bf0] i16 v,h,dc,p: 30% 41% 11% 18%
[libx264 @ 0x143809bf0] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 12% 26% 44%  2%  3%  2%  4%  2%  3%
[libx264 @ 0x143809bf0] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 27% 35% 13%  4%  5%  4%  5%  3%  3%
[libx264 @ 0x143809bf0] i8c dc,h,v,p: 79% 14%  7%  1%
[libx264 @ 0x143809bf0] Weighted P-Frames: Y:41.6% UV:8.7%
[libx264 @ 0x143809bf0] ref P L0: 50.3% 49.7%
[libx264 @ 0x143809bf0] ref B L0: 68.7% 31.3%
[libx264 @ 0x143809bf0] ref B L1: 87.0% 13.0%
[libx264 @ 0x143809bf0] kb/s:1000.65
[aac @ 0x143812a30] Qavg: 672.218
```

Removing the mapping is a bit clumsy, but does seem to work. Is there a fancier way to say "just the one video stream, please" in ffmpeg?

**Comment by EmCNabs** [comment]
Interesting.

Good to know ffmpeg isnt a sentient AI yet. lol

**Comment by BleakleyMcD** [comment]
`-map -map 0:v:0` might make it choose just the first video stream. Haven't tested!

**Comment by eddycolloton** [comment]
yup, this fixes it. The 0:v:0 mapping works with existing jpc_av test files and with the new bowser file. I've updated the code on the main branch to use -map 0:v:0 for video, and sticking with -map 0:a? for audio: https://github.com/JPC-AV/JPC_AV_videoQC/commits/main/
