### ISSUE TITLE
--profile Step2 QCTools error

### ISSUE THREAD

**Issue by EmCNabs** [JPC-AV/JPC_AV_videoQC#50]
--profile Step2 is set to create a qctools report file, however for me it is not out putting the report file to the directory resulting in a "no file found" error.

```
Running command: qcli -i "/Users/medialab/Desktop/JPC_AV_Tests/2012_79_2_224_1a_PM/2012_79_2_224_1a_PM.mkv" -o /Users/medialab/Desktop/JPC_AV_Tests/2012_79_2_224_1a_PM/2012_79_2_224_1a_PM_qc_metadata/2012_79_2_224_1a_PM.qctools.xml.gz
qcli dev build, Oct 12 2023 07:09:34
filters selected: signalstats psnr astats 
[matroska,webm @ 0x7f9723004f80] Stream #4: not enough frames to estimate rate; consider increasing probesize
[matroska,webm @ 0x7f9723004f80] Could not find codec parameters for stream 2 (Attachment: none): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x7f9723004f80] Could not find codec parameters for stream 3 (Attachment: none): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options

analyzing input file... /Users/medialab/Desktop/JPC_AV_Tests/2012_79_2_224_1a_PM/2012_79_2_224_1a_PM.mkv

Unable to check qctools report. No file found at this path: /Users/medialab/Desktop/JPC_AV_Tests/2012_79_2_224_1a_PM/2012_79_2_224_1a_PM_qc_metadata/2012_79_2_224_1a_PM.qctools.xml.gz.

Traceback (most recent call last):
  File "/usr/local/anaconda3/bin/av-spex", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/medialab/github/JPC_AV_videoQC/src/AV_Spex/av_spex_the_file.py", line 538, in main
    write_html_report(video_id,mediaconch_output_path,diff_csv_path,exiftool_output_path,mediainfo_output_path,ffprobe_output_path,html_report_path)
TypeError: write_html_report() missing 2 required positional arguments: 'ffprobe_output_path' and 'html_report_path'
```

**Comment by EmCNabs** [comment]
Tested again with a qctools report I exported direct from qctools, and noticed that script is also looking for an incorrect file extension. It looks for  `2012_79_2_224_1a_PM.qctools.xml.gz.`

When I think it it should be looking for 2012_79_2_224_1a_PM **.mkv.qctools.xml.gz**

**Comment by eddycolloton** [comment]
Two separate issues here.

Issue 1:
av-spex is scripted to create qctools reports with a .qctools.xml.gz extension, without the original video file extension. 
The default sidecar output for QCTools is now just qctools.mkv. So eventually we may need to re-work to output to mkv and extract for qct-parse. 

But for now it's whatever we want it to be, so I'm happy to include the original video file extension going forward if we would like.

Issue 2:
Looks like your terminal output goes directly from:
```analyzing input file... /Users/medialab/Desktop/JPC_AV_Tests/2012_79_2_224_1a_PM/2012_79_2_224_1a_PM.mkv```
To:
```Unable to check qctools report. No file found at this path: ```

If qctools never output the progress bar, then it probably failed to create the report. The python "Traceback" error you got as a result is because of a new html report feature. I'll merge the feature branch tomorrow, which will resolve the issue.

When I run `qcli -i` on `2012_79_2_224_1a_PM.mkv` this is what I get:
```
(JPC_AV) [JPC_AV_videoQC] $ qcli -i /Users/eddycolloton/git/JPC_AV/sample_files/bowser_files/2012_79_2_224_1a_PM/2012_79_2_224_1a_PM.mkv
qcli dev build, Oct 12 2023 07:09:34
filters selected: signalstats psnr astats 
[matroska,webm @ 0x132f04bc0] Stream #4: not enough frames to estimate rate; consider increasing probesize
[matroska,webm @ 0x132f04bc0] Could not find codec parameters for stream 2 (Attachment: none): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x132f04bc0] Could not find codec parameters for stream 3 (Attachment: none): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options

analyzing input file... /Users/eddycolloton/git/JPC_AV/sample_files/bowser_files/2012_79_2_224_1a_PM/2012_79_2_224_1a_PM.mkv
zsh: segmentation fault  qcli -i 
```

No idea what segmentation fault is, but I don't get it on other files when I run `qcli -i` on them. I'll keep troubleshooting this file, see what we can figure it out.

**Comment by eddycolloton** [comment]
As of this merge you shouldn't get the "Traceback error". https://github.com/JPC-AV/JPC_AV_videoQC/commit/6dc13498e2ddc4c2a1e1960fae5260ca09f0939a

This doesn't resolve the issue with `qcli -i` not working w/ 2012_79_2_224_1a_PM.mkv, just stops av-spex from hard exiting when qcli -i says it will output a qctools report, but doesn't.

**Comment by eddycolloton** [comment]
Regarding file naming convention - should I change av-spex default report output from:
 `JPC_AV_01709.qctools.xml.gz` to `JPC_AV_01709.mkv.qctools.xml.gz` ?
@EmCNabs @BleakleyMcD

**Comment by EmCNabs** [comment]
> Regarding file naming convention - should I change av-spex default report output from: `JPC_AV_01709.qctools.xml.gz` to `JPC_AV_01709.mkv.qctools.xml.gz` ? @EmCNabs @BleakleyMcD

I will look at how it runs this week/when I am back in the video lab, and circle back with thoughts on the qctools report file naming.

**Comment by eddycolloton** [comment]
I only get this `segmentation fault` error on 2012_79_2_224_1a_PM.mkv and 2012_79_2_225_1a_PM.mkv when I use `qcli`. I don't get it with the qctools GUI. I've started an issue on the qctools github: https://github.com/bavc/qctools/issues/836

**Comment by eddycolloton** [comment]
👀  https://github.com/bavc/qctools/pull/839
