### ISSUE TITLE
Process cessation -  ValueError: could not convert string to float: 'N/A'

### ISSUE THREAD

**Issue by DSohl** [JPC-AV/JPC_AV_videoQC#53]
I ran av-spex as I left the office last night, doing its magic on six videos. When I came in this morning, it had completed two videos, but stopped on the third of them (and did not proceed to the other three). Here's the readout on that deathly process:

```
Input video file found: /Users/medialab/Desktop/JPC/20240726/JPC_AV_02041/JPC_AV_02041.mkv

|[●▪▪●]| |[●▪▪●]| |[●▪▪●]|

Now processing /Users/medialab/Desktop/JPC/20240726/JPC_AV_02041/JPC_AV_02041.mkv

Directory name "JPC_AV_02041" correctly starts with "JPC_AV".

Metadata files will be written to /Users/medialab/Desktop/JPC/20240726/JPC_AV_02041/JPC_AV_02041_qc_metadata

Files generated by vrecord found. 'JPC_AV_02041_vrecord_metadata' directory created and files moved.
No video stream hash found
No audio stream hash found

Generating video and audio stream hashes. This may take a moment...
FFmpeg 'streamhash' Progress: 100.00%
Video hash = 10bcbea1d4325a9fc3aeffc12a01fec7
Audio hash = 0ce47b4ba7c685260d4f55bfd19be4d3

Embedding video and audio stream hashes to XML in MKV file
Running mkvpropedit:
The file is being analyzed.
The changes are written to the file.



Generating md5 checksum for JPC_AV_02041.mkv via fixity_check.py:
Calculated md5 checksum is 83f80f506a527a73d35f89cee4594fb9

MD5 checksum written to /Users/medialab/Desktop/JPC/20240726/JPC_AV_02041/JPC_AV_02041_2024_07_29_fixity.txt

Using MediaConch policy JPC_AV_NTSC_MKV_2023-11-21.xml

Running command: mediaconch -p /Users/medialab/github/jpc/videoQC/config/JPC_AV_NTSC_MKV_2023-11-21.xml "/Users/medialab/Desktop/JPC/20240726/JPC_AV_02041/JPC_AV_02041.mkv" -oc /Users/medialab/Desktop/JPC/20240726/JPC_AV_02041/JPC_AV_02041_qc_metadata/JPC_AV_02041_mediaconch_output.csv

MediaConch policy failed:
overall: fail
General/Title Exists: fail
General/EncodedBy Exists: fail
General/Description Exists: fail
Audio/Format is FLAC: fail
Audio/CodecID is A_FLAC: fail
Audio/BitRate_Mode is VBR: fail
Audio/ChannelPositions is Front: L R: fail

Running command: exiftool "/Users/medialab/Desktop/JPC/20240726/JPC_AV_02041/JPC_AV_02041.mkv" > /Users/medialab/Desktop/JPC/20240726/JPC_AV_02041/JPC_AV_02041_qc_metadata/JPC_AV_02041_exiftool_output.txt

All specified fields and values found in the Exiftool output.

Running command: mediainfo -f "/Users/medialab/Desktop/JPC/20240726/JPC_AV_02041/JPC_AV_02041.mkv" > /Users/medialab/Desktop/JPC/20240726/JPC_AV_02041/JPC_AV_02041_qc_metadata/JPC_AV_02041_mediainfo_output.txt

All specified fields and values found in the MediaInfo output.

Creating MediaTrace XML file to check custom MKV Tag metadata fields:

Running command: mediainfo --Details=1 --Output=XML "/Users/medialab/Desktop/JPC/20240726/JPC_AV_02041/JPC_AV_02041.mkv" > /Users/medialab/Desktop/JPC/20240726/JPC_AV_02041/JPC_AV_02041_qc_metadata/JPC_AV_02041_mediatrace_output.xml

Some specified MediaTrace fields or values are missing or don't match:
COLLECTION metadata field not found
TITLE metadata field not found
CATALOG_NUMBER metadata field not found
DESCRIPTION metadata field not found
DATE_DIGITIZED metadata field not found
ENCODING_SETTINGS metadata field not found
ENCODED_BY metadata field not found
ORIGINAL_MEDIA_TYPE metadata field not found
DATE_TAGGED metadata field not found
TERMS_OF_USE metadata field not found
_TECHNICAL_NOTES metadata field not found
_ORIGINAL_FPS metadata field not found

Running command: ffprobe -v error -hide_banner -show_format -show_streams -print_format json "/Users/medialab/Desktop/JPC/20240726/JPC_AV_02041/JPC_AV_02041.mkv" > /Users/medialab/Desktop/JPC/20240726/JPC_AV_02041/JPC_AV_02041_qc_metadata/JPC_AV_02041_ffprobe_output.txt

Some specified ffprobe fields or values are missing or don't match:
Encoder Settings No Encoder Settings found, No Signal Flow data embedded

Running command: qcli -i "/Users/medialab/Desktop/JPC/20240726/JPC_AV_02041/JPC_AV_02041.mkv" -o /Users/medialab/Desktop/JPC/20240726/JPC_AV_02041/JPC_AV_02041_qc_metadata/JPC_AV_02041.qctools.xml.gz
qcli dev build, Oct 12 2023 07:09:34
filters selected: signalstats psnr astats 
[matroska,webm @ 0x145607580] Could not find codec parameters for stream 2 (Attachment: none): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x145607580] Could not find codec parameters for stream 3 (Attachment: none): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options

analyzing input file... /Users/medialab/Desktop/JPC/20240726/JPC_AV_02041/JPC_AV_02041.mkv
.................................................. 100 of 100 %
analyzing completed

generating QCTools report... 
.................................................. 100 of 100 %
generating QCTools report... done, in /Users/medialab/Desktop/JPC/20240726/JPC_AV_02041/JPC_AV_02041_qc_metadata/JPC_AV_02041.qctools.xml.gz

Running ffmpeg on JPC_AV_02041.mkv to create access copy JPC_AV_02041_access.mp4

FFmpeg Access Copy Progress: 99.80%Traceback (most recent call last):
  File "/Users/medialab/anaconda3/bin/av-spex", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/medialab/github/jpc/videoQC/src/AV_Spex/av_spex_the_file.py", line 493, in main
    make_access_file(video_path, access_output_path)
  File "/Users/medialab/github/jpc/videoQC/src/AV_Spex/checks/make_access.py", line 51, in make_access_file
    current_frame_ms = float(current_frame_str)
                       ^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'N/A'
                                                                                
(base) /Users/medialab/Desktop/JPC/20240729
```

**Comment by eddycolloton** [comment]
Hi David, This looks very similar to the issue Emily was encountering a few weeks ago: https://github.com/JPC-AV/JPC_AV_videoQC/issues/48

Can you navigate to the "JPC_AV_videoQC" directory where av-spex is installed and run:
``` pip install -e .```

Then run `av-spex --version` and let me know what the output is, please.

**Comment by DSohl** [comment]
Here's what I got:

```
(base) /Users/medialab/github/jpc/videoQC
≈:≈ pip install -e .
Obtaining file:///Users/medialab/github/jpc/videoQC
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Requirement already satisfied: ruamel.yaml==0.18.6 in /Users/medialab/anaconda3/lib/python3.11/site-packages (from AV_Spex==0.3.2) (0.18.6)
Requirement already satisfied: colorlog==6.7.0 in /Users/medialab/anaconda3/lib/python3.11/site-packages (from AV_Spex==0.3.2) (6.7.0)
Requirement already satisfied: art==6.1 in /Users/medialab/anaconda3/lib/python3.11/site-packages (from AV_Spex==0.3.2) (6.1)
Requirement already satisfied: ruamel.yaml.clib>=0.2.7 in /Users/medialab/anaconda3/lib/python3.11/site-packages (from ruamel.yaml==0.18.6->AV_Spex==0.3.2) (0.2.8)
Building wheels for collected packages: AV_Spex
  Building editable for AV_Spex (pyproject.toml) ... done
  Created wheel for AV_Spex: filename=AV_Spex-0.3.2-0.editable-py3-none-any.whl size=28122 sha256=d6c3bdfe6367e21d3a170f519167122caba9825b8143ddbe0768efbc245f009d
  Stored in directory: /private/var/folders/d3/mldpfrlj7ynfp_jjtnrvzmwr0000gr/T/pip-ephem-wheel-cache-7kajlj6h/wheels/45/ba/f0/d36461d0209496d9cc968caf7f3abf3423782935a088578037
Successfully built AV_Spex
Installing collected packages: AV_Spex
  Attempting uninstall: AV_Spex
    Found existing installation: AV_Spex 0.3.2
    Uninstalling AV_Spex-0.3.2:
      Successfully uninstalled AV_Spex-0.3.2
Successfully installed AV_Spex-0.3.2
                                                                                
(base) /Users/medialab/github/jpc/videoQC
```

**Comment by eddycolloton** [comment]
Ok, I think this is the same issue as Emily had, which I added a fix for on 07/12, but you're running ver 0.3.2, which is from 07/08. 

You can pull the most recent code which should resolve the issue. But, I've just removed the access file creation from step1 on the main branch. 

If you don't need the access files, you can simply update the code and run av-spex as you normally would. If you do need av-spex to make these access files, it is a little more complicated. 

There are 2 ways to do this:
1. If you always declare `--profile step1` when you run av-spex, and you would like av-spex to make access files for the time being, just `git checkout` the code from before I removed the access file creation from step1, like this:
```git checkout b4da98b```
(must be run from the "JPC_AV_videoQC" directory)

OR:

2. Update to the most recent version of the code. Then run av-spex with the 'dry run' option, and set the command_config.yaml to step1 like this:
```av-spex --dryrun --profile step1```

Now open the file `/JPC_AV_videoQC/config/command_config.yaml` and change this:
```
outputs:
##  'yes' or 'no'
  access_file: 'no'
  ```
  to this:
```
  outputs:
##  'yes' or 'no'
  access_file: 'yes'
```
Run av-spex as you normally would but without the `--profile step1` flag.

**Comment by eddycolloton** [comment]
Hi @DSohl were you able to resolve or work around this issue? 

Also, could you send me this file? JPC_AV_02041.mkv?

**Comment by DSohl** [comment]
Hey, @eddycolloton, sorry for the delay. Yes, when I omitted the ```--profile step1``` flag, the issue seemed to have gone away. I'll send over JPC_AV_02041 ASAP.

**Comment by eddycolloton** [comment]
Issue creating access file is the same as issue https://github.com/JPC-AV/JPC_AV_videoQC/issues/48
Resolved as of commit: https://github.com/JPC-AV/JPC_AV_videoQC/commits/main/
Marking issue resolved.
