### ISSUE TITLE
add pandas to dependency list?

### ISSUE THREAD

**Issue by BleakleyMcD** [JPC-AV/JPC_AV_videoQC#62]
```
(JPC_AV) /Users/mcdowellb/github/jpc/videoqc_jpc_av
≈:≈ python3 -m pip install -e .
Obtaining file:///Users/mcdowellb/github/jpc/videoqc_jpc_av
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting ruamel.yaml==0.18.6 (from AV_Spex==0.4.7)
  Using cached ruamel.yaml-0.18.6-py3-none-any.whl.metadata (23 kB)
Collecting colorlog==6.7.0 (from AV_Spex==0.4.7)
  Using cached colorlog-6.7.0-py2.py3-none-any.whl.metadata (10 kB)
Collecting art==6.1 (from AV_Spex==0.4.7)
  Using cached art-6.1-py3-none-any.whl.metadata (69 kB)
Collecting lxml==5.2.0 (from AV_Spex==0.4.7)
  Downloading lxml-5.2.0-cp310-cp310-macosx_10_9_universal2.whl.metadata (3.9 kB)
Collecting ruamel.yaml.clib>=0.2.7 (from ruamel.yaml==0.18.6->AV_Spex==0.4.7)
  Using cached ruamel.yaml.clib-0.2.8-cp310-cp310-macosx_13_0_arm64.whl.metadata (2.2 kB)
Using cached art-6.1-py3-none-any.whl (599 kB)
Using cached colorlog-6.7.0-py2.py3-none-any.whl (11 kB)
Downloading lxml-5.2.0-cp310-cp310-macosx_10_9_universal2.whl (8.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.5/8.5 MB 102.3 MB/s eta 0:00:00
Using cached ruamel.yaml-0.18.6-py3-none-any.whl (117 kB)
Using cached ruamel.yaml.clib-0.2.8-cp310-cp310-macosx_13_0_arm64.whl (133 kB)
Building wheels for collected packages: AV_Spex
  Building editable for AV_Spex (pyproject.toml) ... done
  Created wheel for AV_Spex: filename=AV_Spex-0.4.7-0.editable-py3-none-any.whl size=31146 sha256=a6465d77b251267747cafba942f54ec8069bf543d705fc2b17dc7b74d22cd797
  Stored in directory: /private/var/folders/d2/jw6h8v8s7z71ffy2vpkpx0kh0000gq/T/pip-ephem-wheel-cache-boqpz1s5/wheels/53/a8/7a/078bd9c31fd8efee4fd3e98242abb67ff905326929b4803bb3
Successfully built AV_Spex
Installing collected packages: ruamel.yaml.clib, lxml, colorlog, art, ruamel.yaml, AV_Spex
Successfully installed AV_Spex-0.4.7 art-6.1 colorlog-6.7.0 lxml-5.2.0 ruamel.yaml-0.18.6 ruamel.yaml.clib-0.2.8
                                                                                
(JPC_AV) /Users/mcdowellb/github/jpc/videoqc_jpc_av
≈:≈ conda create -n JPC_AV python=3.10.13
WARNING: A conda environment already exists at '/opt/anaconda3/envs/JPC_AV'
Remove existing environment (y/[n])? n


CondaSystemExit: Exiting.

                                                                                
(JPC_AV) /Users/mcdowellb/github/jpc/videoqc_jpc_av
≈:≈ av-spex --help
Traceback (most recent call last):
  File "/opt/anaconda3/envs/JPC_AV/bin/av-spex", line 5, in <module>
    from AV_Spex.av_spex_the_file import main
  File "/Users/mcdowellb/github/jpc/videoqc_jpc_av/src/AV_Spex/av_spex_the_file.py", line 23, in <module>
    from .utils.generate_report import write_html_report
  File "/Users/mcdowellb/github/jpc/videoqc_jpc_av/src/AV_Spex/utils/generate_report.py", line 8, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
                                                                                
(JPC_AV) /Users/mcdowellb/github/jpc/videoqc_jpc_av
≈:≈ 
```

**Comment by BleakleyMcD** [comment]
@eddycolloton also "plotly"

```
(JPC_AV) /Users/mcdowellb/github/jpc/videoqc_jpc_av
≈:≈ python3 -m pip install pandas        
Collecting pandas
  Downloading pandas-2.2.2-cp310-cp310-macosx_11_0_arm64.whl.metadata (19 kB)
Collecting numpy>=1.22.4 (from pandas)
  Downloading numpy-2.1.0-cp310-cp310-macosx_14_0_arm64.whl.metadata (60 kB)
Collecting python-dateutil>=2.8.2 (from pandas)
  Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2024.1-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas)
  Downloading six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
Downloading pandas-2.2.2-cp310-cp310-macosx_11_0_arm64.whl (11.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 104.6 MB/s eta 0:00:00
Downloading numpy-2.1.0-cp310-cp310-macosx_14_0_arm64.whl (5.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 89.1 MB/s eta 0:00:00
Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Downloading pytz-2024.1-py2.py3-none-any.whl (505 kB)
Downloading tzdata-2024.1-py2.py3-none-any.whl (345 kB)
Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: pytz, tzdata, six, numpy, python-dateutil, pandas
Successfully installed numpy-2.1.0 pandas-2.2.2 python-dateutil-2.9.0.post0 pytz-2024.1 six-1.16.0 tzdata-2024.1
                                                                                                                                    
(JPC_AV) /Users/mcdowellb/github/jpc/videoqc_jpc_av
≈:≈ av-spex --help               
Traceback (most recent call last):
  File "/opt/anaconda3/envs/JPC_AV/bin/av-spex", line 5, in <module>
    from AV_Spex.av_spex_the_file import main
  File "/Users/mcdowellb/github/jpc/videoqc_jpc_av/src/AV_Spex/av_spex_the_file.py", line 23, in <module>
    from .utils.generate_report import write_html_report
  File "/Users/mcdowellb/github/jpc/videoqc_jpc_av/src/AV_Spex/utils/generate_report.py", line 9, in <module>
    import plotly.graph_objs as go
ModuleNotFoundError: No module named 'plotly'
                                                                                                                                    
(JPC_AV) /Users/mcdowellb/github/jpc/videoqc_jpc_av
≈:≈ python3 -m pip install plotly
Collecting plotly
  Downloading plotly-5.23.0-py3-none-any.whl.metadata (7.3 kB)
Collecting tenacity>=6.2.0 (from plotly)
  Downloading tenacity-9.0.0-py3-none-any.whl.metadata (1.2 kB)
Collecting packaging (from plotly)
  Downloading packaging-24.1-py3-none-any.whl.metadata (3.2 kB)
Downloading plotly-5.23.0-py3-none-any.whl (17.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 105.3 MB/s eta 0:00:00
Downloading tenacity-9.0.0-py3-none-any.whl (28 kB)
Downloading packaging-24.1-py3-none-any.whl (53 kB)
Installing collected packages: tenacity, packaging, plotly
Successfully installed packaging-24.1 plotly-5.23.0 tenacity-9.0.0
                                                                                                                                    
(JPC_AV) /Users/mcdowellb/github/jpc/videoqc_jpc_av
≈:≈ av-spex --help               
                                                                      
                                                                      
    // | |       ||   / /       //   ) )                              
   //__| |       ||  / /       ((            ___        ___           
  / ___  | ____  || / /          \\        //   ) )   //___) ) \\ / / 
 //    | |       ||/ /             ) )    //___/ /   //         \/ /  
//     | |       |  /       ((___ / /    //         ((____      / /\  
```

**Comment by eddycolloton** [comment]
Yup. These are dependencies from a recent feature branch. Thought I had caught them but maybe they slipped through resolving a merge or something. Pandas and plotly now added to pyproject.toml and version updated: https://github.com/JPC-AV/JPC_AV_videoQC/commit/c965e252fcba451043676726454e20f6815b7838
